import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'com.github.johnrengelman.shadow'
    id 'java-gradle-plugin'
    id 'org.jetbrains.kotlin.jvm' version "$kotlinVersion"
    id 'maven-publish'
    id 'org.jlleitschuh.gradle.ktlint' version '11.4.2'
}

repositories {
    google()
    mavenCentral()
}

def agpVersion = '8.1.1'

gradlePlugin {
    plugins {
        proguardPlugin {
            id = 're.obfuscator.dprotect'
            implementationClass = 'proguard.gradle.plugin.ProGuardPlugin'
        }
    }
}

compileKotlin {
    kotlinOptions.jvmTarget = "17"
}

compileTestKotlin {
    kotlinOptions.jvmTarget = "17"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

configurations {
    fatJar.extendsFrom(implementation)
}

dependencies {
    api project(':base')
    compileOnly ("com.android.tools.build:gradle:$agpVersion") {
        exclude module: 'proguard-gradle'
        exclude module: 'proguard-base'
    }
    compileOnly "com.android.tools.build:gradle-api:$agpVersion"
    implementation 'com.github.zafarkhaja:java-semver:0.9.0'
    testCompileOnly ("com.android.tools.build:gradle:$agpVersion") {
        exclude module: 'proguard-gradle'
        exclude module: 'proguard-base'
    }
    testCompileOnly "com.android.tools.build:gradle-api:$agpVersion"
    testImplementation 'io.kotest:kotest-runner-junit5-jvm:5.8.0'
    testImplementation 'io.kotest:kotest-assertions-core-jvm:5.8.0'
    testImplementation 'io.kotest:kotest-property-jvm:5.8.0'

    testImplementation "io.mockk:mockk:1.13.8"
    testImplementation "commons-io:commons-io:2.11.0"

    fatJar project(":base")
    fatJar 'com.github.zafarkhaja:java-semver:0.9.0'
}

test {
    useJUnitPlatform()
}

def localRepo = file("$buildDir/local-repo")

task fatJar(type: ShadowJar) {
    destinationDirectory.set(file("$rootDir/lib"))
    archiveFileName.set("dprotect-gradle-${version}.jar")
    from sourceSets.main.output
    configurations = [project.configurations.fatJar]
    manifest {
        attributes(
                'Main-Class': 'dprotect.DProtect',
                'Implementation-Version': archiveVersion.get())
    }
}

tasks.withType(Test).configureEach {
    dependsOn fatJar
    systemProperty "local.repo", localRepo.toURI()
    systemProperty "proguard.version", version
    systemProperty "agp.version", agpVersion
}

sourceSets.test {
    resources {
        srcDirs += "$buildDir/fixtures"
    }
}

// Copies selected directories from examples into the test resources to compile during an integration test.
def copyExamples = tasks.register('copyExamples', Copy) {
    from("$rootProject.rootDir/examples") {
        include 'spring-boot/**'
        include 'gradle-kotlin-dsl/**'
        include 'application/**'
    }
    into "$buildDir/fixtures"
}

tasks.named('processTestResources', ProcessResources) {
    dependsOn copyExamples
}

tasks.withType(Test).configureEach {
    dependsOn copyExamples
}

afterEvaluate {
    /*  This project gets two publications:
        - "pluginMaven" is the default from `java-gradle-plugin`
          and must not be automatically published to remote repos.
        - "<project.name>" is created by ProGuard custom logic
          and should have its artifact ID adjusted.
        - we disable publishing of pluginMaven and plugin markers
          to Sonatype only, but KEEP GitHub Packages so the
          plugins { } DSL works with GitHub Packages.
     */
    tasks.withType(AbstractPublishToMaven).matching { task ->
        task.publication.name == 'pluginMaven' ||
            task.name =~ /^publish(.*)PluginMarkerMavenPublicationToSonatypeRepository$/
    } each {task ->
        task.enabled = false
    }

    publishing {
        publications.getByName(project.name) {
            pom {
                description = 'Gradle plugin for dProtect, the enhanced Android code obfuscator based on Proguard™'
            }
        }
    }
}
